// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_input_field`, `is_sys_inputs`, `walk_for_inputs`

/// Compiles a Typst template and returns the PDF bytes.
///
/// - `template`   : main .typ file content (UTF-8)
/// - `inputs`     : data injected as sys.inputs (HashMap -> Dict)
/// - `fonts`      : additional font bytes (.ttf/.otf)
/// - `extra_files`: extra files (images, sub-templates)
Future<CompileResult> compile({
  required String template,
  Map<String, String>? inputs,
  required List<Uint8List> fonts,
  required List<TypstFileInput> extraFiles,
}) => RustLib.instance.api.crateApiTypstCompilerCompile(
  template: template,
  inputs: inputs,
  fonts: fonts,
  extraFiles: extraFiles,
);

/// Discovers all `sys.inputs.at(...)` calls in a Typst template via AST analysis.
/// No compilation needed — pure syntax analysis.
Future<List<DiscoveredInput>> discoverInputs({required String source}) =>
    RustLib.instance.api.crateApiTypstCompilerDiscoverInputs(source: source);

/// Result of a successful compilation.
class CompileResult {
  /// Generated PDF bytes — ready to save or display.
  final Uint8List pdfBytes;

  /// Non-fatal warnings emitted by the Typst compiler.
  final List<String> warnings;

  const CompileResult({required this.pdfBytes, required this.warnings});

  @override
  int get hashCode => pdfBytes.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompileResult &&
          runtimeType == other.runtimeType &&
          pdfBytes == other.pdfBytes &&
          warnings == other.warnings;
}

/// A discovered input field from a Typst template.
class DiscoveredInput {
  final String name;
  final bool required_;
  final String? defaultValue;

  const DiscoveredInput({
    required this.name,
    required this.required_,
    this.defaultValue,
  });

  @override
  int get hashCode =>
      name.hashCode ^ required_.hashCode ^ defaultValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          required_ == other.required_ &&
          defaultValue == other.defaultValue;
}

/// Extra file (image, .typ include) for the compiler.
/// `path` is the virtual path used in the template (e.g. "logo.png")
class TypstFileInput {
  final String path;
  final Uint8List data;

  const TypstFileInput({required this.path, required this.data});

  @override
  int get hashCode => path.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstFileInput &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          data == other.data;
}
